### PR TITLE
Add custom skip label for compatibility with autorebase bot

### PR DESCRIPTION
**Pull request by mzyy94**
Add skip option to environment variable. It is more compatible with an autorebase bot such as Dependabot to use skip label.

### CODE REVIEW

**Comment by saneyuki** [comment]
@mzyy94 

Can I ask you some questions?

> It is more compatible with an autorebase bot such as Dependabot to use skip label.

What is the concrete scenario? I'm not sure about all features of https://dependabot.com/. I could not read what the situation you image.

**Comment by mzyy94** [comment]
Dependabot has auto rebase feature. https://twitter.com/dependabot/status/902811039464607744
So it's not necessary to check mergeable state.

**Comment by saneyuki** [comment]
@mzyy94 

> Dependabot has auto rebase feature. https://twitter.com/dependabot/status/902811039464607744
> So it's not necessary to check mergeable state.

Okay. I understand dependabot rebase its pull request automatically.
But I still cannot understand the situation which this action should skip to check for their PRs.

Could you describe what you expected scenario and the current problem?

**Comment by mzyy94** [comment]
Dependabot will automatically rebase a PR conflicted. After completing the rebase, a label `S-needs-rebase` still remains when this github-action-detect-unmergeable labeled it, because Dependabot will not remove any labels. It's not clean enough in Pull request list page that a PR which is mergeable has a label `S-needs-rebase`. So I proposed this PR.

**Comment by saneyuki** [comment]
@mzyy94 

Okay. I see your background. By your scenario, 

- I seem that it would be more better to:
    - create a new action to remove `S-needs-rebase` label from a PR opened by dependabot.
    - Or add the feature to this action that detect & remove `S-needs-rebase` from all mergeable PRs.
- I feel `LABEL_SKIP_CHECKING` is not good choice for your scenario.
    - It might be useful, but I don't seem this background is nice for it.

**Comment by saneyuki** [comment]
> Or add the feature to this action that detect & remove S-needs-rebase from all mergeable PRs.

I feel we may be able to create a such action with using the combination of  [`on=pull_request`](https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#events-supported-in-workflow-files) and [`action=synchronize`](https://developer.github.com/v3/activity/events/types/#pullrequestevent).

**Comment by saneyuki** [comment]
With new GitHub Action workflow, we can ignore a pattern which triggers an action [by a workflow definition](https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-restricting-the-workflow-run-to-specific-refs-and-paths)

For this purpose, especially dependabot, we can ignore some branch name on the repository by this pattern. We don't have to support this feature by this action. So I'll close this.

**Pull request closed without merging**
